//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34209
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FollowMe.Enums
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TargetLocation", Namespace="http://schemas.datacontract.org/2004/07/FollowMe.Enums")]
    public enum TargetLocation : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TopLeft = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TopCenter = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TopRight = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CenterLeft = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CenterCenter = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CenterRight = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BottomLeft = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BottomCenter = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BottomRight = 9,
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IRemoteControl")]
public interface IRemoteControl
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemoteControl/Start", ReplyAction="http://tempuri.org/IRemoteControl/StartResponse")]
    void Start();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemoteControl/Start", ReplyAction="http://tempuri.org/IRemoteControl/StartResponse")]
    System.Threading.Tasks.Task StartAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemoteControl/Stop", ReplyAction="http://tempuri.org/IRemoteControl/StopResponse")]
    void Stop();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemoteControl/Stop", ReplyAction="http://tempuri.org/IRemoteControl/StopResponse")]
    System.Threading.Tasks.Task StopAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemoteControl/GetPersonLocation", ReplyAction="http://tempuri.org/IRemoteControl/GetPersonLocationResponse")]
    FollowMe.Enums.TargetLocation GetPersonLocation();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemoteControl/GetPersonLocation", ReplyAction="http://tempuri.org/IRemoteControl/GetPersonLocationResponse")]
    System.Threading.Tasks.Task<FollowMe.Enums.TargetLocation> GetPersonLocationAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemoteControl/GetDangerLocation", ReplyAction="http://tempuri.org/IRemoteControl/GetDangerLocationResponse")]
    FollowMe.Enums.TargetLocation GetDangerLocation();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemoteControl/GetDangerLocation", ReplyAction="http://tempuri.org/IRemoteControl/GetDangerLocationResponse")]
    System.Threading.Tasks.Task<FollowMe.Enums.TargetLocation> GetDangerLocationAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IRemoteControlChannel : IRemoteControl, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class RemoteControlClient : System.ServiceModel.ClientBase<IRemoteControl>, IRemoteControl
{
    
    public RemoteControlClient()
    {
    }
    
    public RemoteControlClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public RemoteControlClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RemoteControlClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RemoteControlClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void Start()
    {
        base.Channel.Start();
    }
    
    public System.Threading.Tasks.Task StartAsync()
    {
        return base.Channel.StartAsync();
    }
    
    public void Stop()
    {
        base.Channel.Stop();
    }
    
    public System.Threading.Tasks.Task StopAsync()
    {
        return base.Channel.StopAsync();
    }
    
    public FollowMe.Enums.TargetLocation GetPersonLocation()
    {
        return base.Channel.GetPersonLocation();
    }
    
    public System.Threading.Tasks.Task<FollowMe.Enums.TargetLocation> GetPersonLocationAsync()
    {
        return base.Channel.GetPersonLocationAsync();
    }
    
    public FollowMe.Enums.TargetLocation GetDangerLocation()
    {
        return base.Channel.GetDangerLocation();
    }
    
    public System.Threading.Tasks.Task<FollowMe.Enums.TargetLocation> GetDangerLocationAsync()
    {
        return base.Channel.GetDangerLocationAsync();
    }
}
